alexandria:
  initiator:
    gitlab:
      sources[0]:
        id: 3
        name: dummy
        url: https://gitlab.com/
        group-id: 16038523
        accessUsername: example
        accessToken: example
        #repositoryNamePattern: #Regex for search pattern.
        #branchNamePattern: #Regex for search Pattern. Default search always avaiable
