spring:
  datasource:
    url: jdbc:postgresql://123db:5432/postgres
    username: postgres
    password: example
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
alexandria:
  sharedfolder: /alexandriadata